const SET_MOVIES = `SET_MOVIES`;
const SET_PROMO_MOVIE = `SET_PROMO_MOVIE`;
const SET_ACTIVE_FILTER = `SET_ACTIVE_FILTER`;
const INCREASE_MOVIES_COUNTER = `INCREASE_MOVIES_COUNTER`;

export {
  SET_MOVIES,
  SET_PROMO_MOVIE,
  SET_ACTIVE_FILTER,
  INCREASE_MOVIES_COUNTER,
};

