const SET_MOVIES = `SET_MOVIES`;
const UPDATE_MOVIE = `UPDATE_MOVIE`;
const SET_PROMO_MOVIE = `SET_PROMO_MOVIE`;
const SET_ACTIVE_FILTER = `SET_ACTIVE_FILTER`;
const INCREASE_MOVIES_COUNTER = `INCREASE_MOVIES_COUNTER`;
const SET_FAVORITE = `SET_FAVORITE`;
const ADD_TO_FAVORITE = `ADD_TO_FAVORITE`;

export {
  SET_MOVIES,
  UPDATE_MOVIE,
  SET_PROMO_MOVIE,
  SET_ACTIVE_FILTER,
  INCREASE_MOVIES_COUNTER,
  SET_FAVORITE,
  ADD_TO_FAVORITE,
};

