export const ActionTypes = {
  SET_MOVIES: `SET_MOVIES`,
  SET_PROMO_MOVIE: `SET_PROMO_MOVIE`,
  SET_ACTIVE_FILTER: `SET_ACTIVE_FILTER`,
  INCREASE_MOVIES_COUNTER: `INCREASE_MOVIES_COUNTER`,
  SET_IS_AUTHORIZED: `SET_IS_AUTHORIZED`,
  SET_FETCHING_MOVIES: `SET_FETCHING_MOVIES`,
  SET_FETCHING_PROMO: `SET_FETCHING_PROMO`,
};
