export const ActionTypes = {
  SET_MOVIES: `SET_MOVIES`,
  SET_PROMO_MOVIE: `SET_PROMO_MOVIE`,
  SET_ACTIVE_FILTER: `SET_ACTIVE_FILTER`,
  SET_MOVIES_COUNTER: `SET_MOVIES_COUNTER`,
  SET_IS_AUTHORIZED: `SET_IS_AUTHORIZED`,
  SET_FETCHING: `SET_FETCHING`,
};
